#!/usr/bin/env bash

set -euo pipefail

this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)

notebooks=(
    "radar/EstimateRainfall.ipynb"
)

pushd "${this_dir}/notebooks"
for n in ${notebooks[@]}; do
    jupyter nbconvert --to notebook --execute --output /tmp/foo "${n}"
    python ../check_notebook.py /tmp/foo.ipynb
done
popd
