#!/usr/bin/env bash

set -euo pipefail

this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)

notebooks=(
    "meteosim/check_ra_1.ipynb"
    "radar/EstimateRainfall.ipynb"
    "radar/cfradar.ipynb"
    "radar/ckan.ipynb"
    "radar/netcdf_howto.ipynb"
    "radar/rain_anim.ipynb"
    "radar/try_warp.ipynb"
)

pushd "${this_dir}/notebooks"
for n in ${notebooks[@]}; do
    jupyter nbconvert --ExecutePreprocessor.timeout=300 --to notebook --execute --output /tmp/foo "${n}"
    python ../check_notebook.py /tmp/foo.ipynb
done
popd
